# Generated by Django 2.2.6 on 2019-10-08 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=60, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=60)),
                ('street_name', models.TextField()),
                ('suburb', models.TextField(unique=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Must be valid postcode in formats 12345 or 12345-1234', regex='^(^[0-9]{5}(?:-[0-9]{4})?$)?$)')])),
                ('state', models.CharField(blank=True, max_length=200)),
                ('phone_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be upto 10 digits', regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
